# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 286)
        MainWindow.setStyleSheet("#LCD {\n"
"    background-color: black;\n"
"}")
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD.setGeometry(QtCore.QRect(160, 20, 481, 111))
        self.LCD.setAutoFillBackground(False)
        self.LCD.setLineWidth(1)
        self.LCD.setSmallDecimalPoint(True)
        self.LCD.setDigitCount(5)
        self.LCD.setMode(QtWidgets.QLCDNumber.Dec)
        self.LCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.LCD.setProperty("value", 1600.0)
        self.LCD.setProperty("intValue", 1600)
        self.LCD.setObjectName("LCD")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
